import { Currency, Translations } from './types';

export const CURRENCIES: Currency[] = [
  { code: 'TRY', symbol: '₺', name: 'Türk Lirası' },
  { code: 'USD', symbol: '$', name: 'US Dollar' },
  { code: 'EUR', symbol: '€', name: 'Euro' },
  { code: 'GBP', symbol: '£', name: 'British Pound' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
];

export const TRANSLATIONS: Translations = {
  tr: {
    balanceTitle: 'BAKİYE VE HAREKETLER',
    monthEndBalance: 'Ay Sonu Bakiyesi',
    income: 'GELİR',
    expense: 'GİDER',
    transactionsTitle: 'Bu Ayın İşlemleri',
    emptyTransactions: 'Henüz işlem yok. + butonuna basarak ekleyin.',
    analysisTitle: 'Mali Durum',
    analysisSubtitle: 'Aylık gelir ve gider analizi.',
    calendarTitle: 'Takvim',
    calendarSubtitle: 'Günlük harcama ve mesai takibi.',
    upcomingPayments: 'Yaklaşan Ödemeler',
    noUpcoming: 'Yaklaşan ödeme bulunmamaktadır.',
    settingsTitle: 'Ayarlar',
    settingsSubtitle: 'Tercihler ve seçenekler.',
    currency: 'Para Birimi',
    language: 'Dil / Language',
    notifications: 'Bildirimler',
    enableNotifications: 'Ödeme Bildirimleri',
    notificationDesc: 'Yaklaşan ödemeler için otomatik uyarı al.',
    deleteTitle: 'Emin misiniz?',
    deleteDesc: 'işlemini silmek üzeresiniz. Bu işlem geri alınamaz.',
    cancel: 'Vazgeç',
    delete: 'Evet, Sil',
    edit: 'Düzenle',
    addNew: 'Yeni Ekle',
    amountLabel: 'Tutar',
    dailyAmountLabel: 'Günlük Tutar',
    titleLabel: 'Açıklama / Başlık',
    dateLabel: 'Tarih',
    titlePlaceholder: 'örn. Kira, Fatura...',
    recurring: 'Düzenli Tekrar',
    recurringSubtitle: 'Bu işlemi otomatik tekrarla',
    frequency: 'Sıklık',
    daily: 'Günlük',
    weekly: 'Haftalık',
    monthly: 'Aylık',
    duration: 'Süre',
    day: 'Gün',
    month: 'Ay',
    restriction: 'Kısıtlama',
    weekdays: 'Sadece Hafta İçi',
    save: 'Kaydet',
    update: 'Güncelle',
    incomeLabel: 'Gelir',
    expenseLabel: 'Gider',
    home: 'Ana Sayfa',
    analysis: 'Analiz',
    calculatorMode: 'Günlük Hesaplayıcı',
    calcSubtitle: 'Günlük tutarı aylığa çevir',
    fiveDays: '5 Gün (Hafta İçi)',
    sixDays: '6 Gün (Cmt Dahil)',
    totalMonthly: 'Aylık Toplam',
    workDaysCount: 'İş Günü',
    netStatus: 'Net Durum',
    positive: 'Pozitif',
    negative: 'Negatif',
    notificationTitle: 'Hatırlatıcı',
    notificationBody: 'ödemesi yaklaşıyor!',
    overtimeTitle: 'Mesai Ekle',
    netSalaryLabel: 'Aylık Net Maaş',
    hourlyRateLabel: 'Saatlik Ücret',
    multiplierLabel: 'Mesai Türü',
    multiplier15: '1.5 Katı (Normal)',
    multiplier20: '2.0 Katı (Pazar/Bayram)',
    durationLabel: 'Çalışma Süresi',
    calculatedOvertime: 'Hesaplanan Mesai',
    addOvertime: 'Mesaiyi Ekle',
    hour: 'Saat',
    minute: 'Dakika',
    groupLabel: 'Grup / Etiket',
    noGroup: 'Grupsuz',
    newGroup: 'Yeni Grup',
    createGroupTitle: 'Yeni Grup Oluştur',
    groupNamePlaceholder: 'örn. Krediler, Tatil...',
    create: 'Oluştur',
    itemsCount: 'İşlem',
    total: 'Toplam',
    enableAlert: 'Bildirim Al',
    themeTitle: 'Görünüm',
    darkMode: 'Karanlık Mod',
    reminderDays: 'Hatırlatma Süresi',
    daysBefore: 'gün önce',
    holidayTitle: 'Tatil Günleri',
    holidayDesc: 'Haftalık izin günlerinizi seçin',
    mon: 'Pzt', tue: 'Sal', wed: 'Çar', thu: 'Per', fri: 'Cum', sat: 'Cmt', sun: 'Paz',
    appTitle: 'Finansmanım',
    appSubtitle: 'Global Finance',
    
    // ONBOARDING
    welcomeTitle: 'Hoş Geldiniz',
    welcomeSubtitle: 'Finansal özgürlüğünüze ilk adım.',
    salaryQuestion: 'Aylık Net Maaşınız Ne Kadar?',
    salaryDesc: 'Bu bilgi bütçe planlaması ve saatlik ücret hesaplaması için kullanılacak.',
    skip: 'Atla',
    next: 'İleri',
    finish: 'Tamamla',
    workHoursTitle: 'Aylık Çalışma Saati',
    workHoursDesc: 'Standart: 225 saat (Günde 7.5 saat x 30 gün)',
    salaryDayTitle: 'Maaş Günü',
    salaryDayDesc: 'Maaşınızı ayın kaçında alıyorsunuz?',
    salaryInfoCard: 'Maaş Bilgisi',
    salaryDate: 'Maaş Günü',
    everyMonth: 'Her ayın',
    workHours: 'Çalışma Saati',
    salaryTxTitle: 'Maaş',
    paymentToday: 'Bugün ödemesi var!',
    paymentSoon: 'gün sonra ödemesi var!',
    alertSubtitle: 'Bugün ve seçilen gün kadar önce hatırlat',
    salarySettings: 'Maaş Hesaplama',
    notificationSettings: 'Ödeme Bildirimleri'
  },
  en: {
    balanceTitle: 'BALANCE & ACTIVITY',
    monthEndBalance: 'Month End Balance',
    income: 'INCOME',
    expense: 'EXPENSE',
    transactionsTitle: 'Transactions',
    emptyTransactions: 'No transactions yet. Tap + to add.',
    analysisTitle: 'Financial Status',
    analysisSubtitle: 'Monthly income and expense analysis.',
    calendarTitle: 'Calendar',
    calendarSubtitle: 'Daily expense and overtime tracking.',
    upcomingPayments: 'Upcoming Payments',
    noUpcoming: 'No upcoming payments.',
    settingsTitle: 'Settings',
    settingsSubtitle: 'Preferences and options.',
    currency: 'Currency',
    language: 'Language',
    notifications: 'Notifications',
    enableNotifications: 'Payment Notifications',
    notificationDesc: 'Get automatic alerts for upcoming payments.',
    deleteTitle: 'Are you sure?',
    deleteDesc: 'transaction will be deleted. This cannot be undone.',
    cancel: 'Cancel',
    delete: 'Yes, Delete',
    edit: 'Edit',
    addNew: 'Add New',
    amountLabel: 'Amount',
    dailyAmountLabel: 'Daily Amount',
    titleLabel: 'Description / Title',
    dateLabel: 'Date',
    titlePlaceholder: 'e.g. Grocery, Rent...',
    recurring: 'Recurring',
    recurringSubtitle: 'Repeat this transaction automatically',
    frequency: 'Frequency',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    duration: 'Duration',
    day: 'Day',
    month: 'Month',
    restriction: 'Restriction',
    weekdays: 'Weekdays Only',
    save: 'Save',
    update: 'Update',
    incomeLabel: 'Income',
    expenseLabel: 'Expense',
    home: 'Home',
    analysis: 'Analysis',
    calculatorMode: 'Daily Calculator',
    calcSubtitle: 'Convert daily to monthly',
    fiveDays: '5 Days (Weekdays)',
    sixDays: '6 Days (Inc. Sat)',
    totalMonthly: 'Monthly Total',
    workDaysCount: 'Work Days',
    netStatus: 'Net Status',
    positive: 'Positive',
    negative: 'Negative',
    notificationTitle: 'Reminder',
    notificationBody: 'payment is coming up!',
    overtimeTitle: 'Add Overtime',
    netSalaryLabel: 'Monthly Net Salary',
    hourlyRateLabel: 'Hourly Rate',
    multiplierLabel: 'Overtime Type',
    multiplier15: '1.5x (Normal)',
    multiplier20: '2.0x (Sunday/Holiday)',
    durationLabel: 'Work Duration',
    calculatedOvertime: 'Calculated Pay',
    addOvertime: 'Add Overtime',
    hour: 'Hour',
    minute: 'Minute',
    groupLabel: 'Group / Tag',
    noGroup: 'No Group',
    newGroup: 'New Group',
    createGroupTitle: 'Create New Group',
    groupNamePlaceholder: 'e.g. Loans, Vacation...',
    create: 'Create',
    itemsCount: 'Items',
    total: 'Total',
    enableAlert: 'Enable Alert',
    themeTitle: 'Appearance',
    darkMode: 'Dark Mode',
    reminderDays: 'Reminder Time',
    daysBefore: 'days before',
    holidayTitle: 'Rest Days',
    holidayDesc: 'Select your weekly rest days',
    mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat', sun: 'Sun',
    appTitle: 'My Finance',
    appSubtitle: 'Global Finance',

    // ONBOARDING
    welcomeTitle: 'Welcome',
    welcomeSubtitle: 'First step to financial freedom.',
    salaryQuestion: 'What is your Monthly Net Salary?',
    salaryDesc: 'This info is used for budget planning and hourly rate calculation.',
    skip: 'Skip',
    next: 'Next',
    finish: 'Finish',
    workHoursTitle: 'Monthly Work Hours',
    workHoursDesc: 'Standard: 225 hours (7.5 hours/day x 30 days)',
    salaryDayTitle: 'Salary Day',
    salaryDayDesc: 'On which day of the month do you receive your salary?',
    salaryInfoCard: 'Salary Info',
    salaryDate: 'Salary Day',
    everyMonth: 'Every month on',
    workHours: 'Work Hours',
    salaryTxTitle: 'Salary',
    paymentToday: 'Payment is today!',
    paymentSoon: 'days before!',
    alertSubtitle: 'Remind today & before',
    salarySettings: 'Salary Calculation',
    notificationSettings: 'Payment Notifications'
  }
};